/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SIMPCP_H_RPCGEN
#define _SIMPCP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct coordenada_proxy {
	double latitude;
	double longitude;
};
typedef struct coordenada_proxy coordenada_proxy;

#define SIMP_CLIENT 555555556
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define CitySearch_proxy 1
extern  char ** citysearch_proxy_1(char **, CLIENT *);
extern  char ** citysearch_proxy_1_svc(char **, struct svc_req *);
#define LatLongSearch_proxy 2
extern  char ** latlongsearch_proxy_1(coordenada_proxy *, CLIENT *);
extern  char ** latlongsearch_proxy_1_svc(coordenada_proxy *, struct svc_req *);
extern int simp_client_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CitySearch_proxy 1
extern  char ** citysearch_proxy_1();
extern  char ** citysearch_proxy_1_svc();
#define LatLongSearch_proxy 2
extern  char ** latlongsearch_proxy_1();
extern  char ** latlongsearch_proxy_1_svc();
extern int simp_client_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_coordenada_proxy (XDR *, coordenada_proxy*);

#else /* K&R C */
extern bool_t xdr_coordenada_proxy ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SIMPCP_H_RPCGEN */
