/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SIMPSP_H_RPCGEN
#define _SIMPSP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct coordenada {
	double latitude;
	double longitude;
};
typedef struct coordenada coordenada;

#define SIMP_SERVER 555555557
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define CitySearch 1
extern  char ** citysearch_1(char **, CLIENT *);
extern  char ** citysearch_1_svc(char **, struct svc_req *);
#define LatLongSearch 2
extern  char ** latlongsearch_1(coordenada *, CLIENT *);
extern  char ** latlongsearch_1_svc(coordenada *, struct svc_req *);
extern int simp_server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CitySearch 1
extern  char ** citysearch_1();
extern  char ** citysearch_1_svc();
#define LatLongSearch 2
extern  char ** latlongsearch_1();
extern  char ** latlongsearch_1_svc();
extern int simp_server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_coordenada (XDR *, coordenada*);

#else /* K&R C */
extern bool_t xdr_coordenada ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SIMPSP_H_RPCGEN */
