/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "simpCP.h"

bool_t
xdr_coordenada_proxy (XDR *xdrs, coordenada_proxy *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	return TRUE;
}
