/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "simpSP.h"

bool_t
xdr_coordenada (XDR *xdrs, coordenada *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	return TRUE;
}
